# Generated by Django 5.1.2 on 2025-05-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0005_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
    ]
