# Generated by Django 5.2.1 on 2026-05-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0008_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
